server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/p2p?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: a111
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapping/*.xml
  type-aliases-package: com.qf.sy
#pagehelper:
#  reasonable: true
#  support-methods-arguments: true
#  page-size-zero: true
#  params: count=countSql
